version: '3.9'
networks:
  basic:
services:
#  front:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#      target: front
#    container_name: greaterwms_front
#    image: greaterwms/greaterwms:front
#    restart: always
#    privileged: true
#    ports:
#      - '8080:8080'
#    volumes:
#      - ./templates:/GreaterWMS/templates:rw
#      - ./web_start.sh:/GreaterWMS/templates/web_start.sh
#    networks:
#      - basic
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jiaju_django
    image: jiaju:latest
    restart: always
    privileged: true
#    depends_on:
#      - front
    volumes:
      - ./:/jiaju/:rw
      - ./templates:/jiaju/templates:rw
      - ./static:/jiaju/static:rw
      #- ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - '9100:9100'
    environment:
      PYTHONUNBUFFERED: 1
      command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - basic